Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Primeiro "Olá, Mundo!"
// Autor(a)    : Murilo Oliveira
// Data atual  : 21/07/2022
Var
  N1, N2, S: Inteiro
Inicio
 Escreva("Informe um número: ")
 Leia(N1)
 Escreva("Informe outro número: ")
 Leia(N2)
 S<-N1+N2
 Escreval
 Escreval("A soma entre",N1," e",N2," é igual a:",S,"!")
 Fimalgoritmo